// React
import { useEffect } from "react";

// Hooks
import useIsMobile from "../../../hooks/useIsMobile";

// Layouts and Components
import MobileTestSimulator from "../components/mobile/MobileTestSimulator";
import DesktopTestSimulator from "../components/desktop/DesktopTestSimulator";
import useTestStore from "../store/useTestStore";
import useTestTimerStore from "../store/useTestTimerStore";

// Sample Data
const dummyData = {
  responseTxt: "success",
  message: "Total Found: 1",
  obj: [
    {
      testId: 5509,
      testName: "NEET UG 2025 COMPLETE MOCK TEST 2",
      testType: 3,
      testOption: 3,
      totalTime: 180,
      noQuestionAttempt: 0,
      remainingTime: 10800,
      lastQuestionIndex: 0,
      sectionLock: "No_Lock",
      sectionSet: [
        {
          sectionName: "Physics",
          questionNumbers: [
            { questionIndex: 0, questionId: 300001 },
            { questionIndex: 1, questionId: 300002 },
            { questionIndex: 2, questionId: 300003 },
            { questionIndex: 3, questionId: 300004 },
            { questionIndex: 4, questionId: 300005 },
            { questionIndex: 5, questionId: 300006 },
            { questionIndex: 6, questionId: 300007 },
          ],
        },
        {
          sectionName: "Chemistry",
          questionNumbers: [
            { questionIndex: 7, questionId: 300008 },
            { questionIndex: 8, questionId: 300009 },
            { questionIndex: 9, questionId: 300010 },
            { questionIndex: 10, questionId: 300011 },
            { questionIndex: 11, questionId: 300012 },
            { questionIndex: 12, questionId: 300013 },
            { questionIndex: 13, questionId: 300014 },
            { questionIndex: 14, questionId: 300015 },
          ],
        },
        {
          sectionName: "Biology",
          questionNumbers: [
            { questionIndex: 15, questionId: 300016 },
            { questionIndex: 16, questionId: 300017 },
            { questionIndex: 17, questionId: 300018 },
            { questionIndex: 18, questionId: 300019 },
            { questionIndex: 19, questionId: 300020 },
          ],
        },
      ],
      questionSet: [
        {
          questionId: 300001,
          questionDisplayId: "1011905057",
          questionType: "Multiple-Choice",
          questionTypeLabel: "Multiple Choice",
          sectionId: 565,
          sectionName: "Physics",
          sectionOrder: 1,
          sectionTime: 0,
          topicId: "1029",
          timeSpent: 0,
          correctAnswerMarks: 4,
          incorrectAnswerMarks: -1,
          notAnswerMarks: 0,
          questionBody: "Q1. What is Newton's first law?",
          responseChoice: [
            { responseId: "A", responseText: "Option A" },
            { responseId: "B", responseText: "Option B" },
            { responseId: "C", responseText: "Option C" },
            { responseId: "D", responseText: "Option D" },
          ],
          backgroundImg: "url('./not-visited.png')",
          cssName: "qbg-not-visited",
          noQuestionAttempt: 0,
          noQuestion: 7,
        },
        {
          questionId: 300002,
          questionDisplayId: "1011905058",
          questionType: "Multiple-Choice",
          questionTypeLabel: "Multiple Choice",
          sectionId: 565,
          sectionName: "Physics",
          sectionOrder: 1,
          sectionTime: 0,
          topicId: "1030",
          timeSpent: 0,
          correctAnswerMarks: 4,
          incorrectAnswerMarks: -1,
          notAnswerMarks: 0,
          questionBody: "Q2. Define kinetic energy.",
          responseChoice: [
            { responseId: "A", responseText: "Option A" },
            { responseId: "B", responseText: "Option B" },
            { responseId: "C", responseText: "Option C" },
            { responseId: "D", responseText: "Option D" },
          ],
          backgroundImg: "url('./not-visited.png')",
          cssName: "qbg-not-visited",
          noQuestionAttempt: 0,
          noQuestion: 7,
        },
        {
          questionId: 300003,
          questionDisplayId: "1011905059",
          questionType: "Multiple-Choice",
          questionTypeLabel: "Multiple Choice",
          sectionId: 565,
          sectionName: "Physics",
          sectionOrder: 1,
          sectionTime: 0,
          topicId: "1031",
          timeSpent: 0,
          correctAnswerMarks: 4,
          incorrectAnswerMarks: -1,
          notAnswerMarks: 0,
          questionBody: "Q3. Formula for potential energy?",
          responseChoice: [
            { responseId: "A", responseText: "Option A" },
            { responseId: "B", responseText: "Option B" },
            { responseId: "C", responseText: "Option C" },
            { responseId: "D", responseText: "Option D" },
          ],
          backgroundImg: "url('./not-visited.png')",
          cssName: "qbg-not-visited",
          noQuestionAttempt: 0,
          noQuestion: 7,
        },
        {
          questionId: 300004,
          questionDisplayId: "1011905060",
          questionType: "Multiple-Choice",
          questionTypeLabel: "Multiple Choice",
          sectionId: 565,
          sectionName: "Physics",
          sectionOrder: 1,
          sectionTime: 0,
          topicId: "1032",
          timeSpent: 0,
          correctAnswerMarks: 4,
          incorrectAnswerMarks: -1,
          notAnswerMarks: 0,
          questionBody: "Q4. Unit of power?",
          responseChoice: [
            { responseId: "A", responseText: "Option A" },
            { responseId: "B", responseText: "Option B" },
            { responseId: "C", responseText: "Option C" },
            { responseId: "D", responseText: "Option D" },
          ],
          backgroundImg: "url('./not-visited.png')",
          cssName: "qbg-not-visited",
          noQuestionAttempt: 0,
          noQuestion: 7,
        },
        {
          questionId: 300005,
          questionDisplayId: "1011905061",
          questionType: "Multiple-Choice",
          questionTypeLabel: "Multiple Choice",
          sectionId: 565,
          sectionName: "Physics",
          sectionOrder: 1,
          sectionTime: 0,
          topicId: "1033",
          timeSpent: 0,
          correctAnswerMarks: 4,
          incorrectAnswerMarks: -1,
          notAnswerMarks: 0,
          questionBody: "Q5. What is current?",
          responseChoice: [
            { responseId: "A", responseText: "Option A" },
            { responseId: "B", responseText: "Option B" },
            { responseId: "C", responseText: "Option C" },
            { responseId: "D", responseText: "Option D" },
          ],
          backgroundImg: "url('./not-visited.png')",
          cssName: "qbg-not-visited",
          noQuestionAttempt: 0,
          noQuestion: 7,
        },
        {
          questionId: 300006,
          questionDisplayId: "1011905062",
          questionType: "Multiple-Choice",
          questionTypeLabel: "Multiple Choice",
          sectionId: 565,
          sectionName: "Physics",
          sectionOrder: 1,
          sectionTime: 0,
          topicId: "1034",
          timeSpent: 0,
          correctAnswerMarks: 4,
          incorrectAnswerMarks: -1,
          notAnswerMarks: 0,
          questionBody: "Q6. Ohm's Law states?",
          responseChoice: [
            { responseId: "A", responseText: "Option A" },
            { responseId: "B", responseText: "Option B" },
            { responseId: "C", responseText: "Option C" },
            { responseId: "D", responseText: "Option D" },
          ],
          backgroundImg: "url('./not-visited.png')",
          cssName: "qbg-not-visited",
          noQuestionAttempt: 0,
          noQuestion: 7,
        },
        {
          questionId: 300007,
          questionDisplayId: "1011905063",
          questionType: "Multiple-Choice",
          questionTypeLabel: "Multiple Choice",
          sectionId: 565,
          sectionName: "Physics",
          sectionOrder: 1,
          sectionTime: 0,
          topicId: "1035",
          timeSpent: 0,
          correctAnswerMarks: 4,
          incorrectAnswerMarks: -1,
          notAnswerMarks: 0,
          questionBody: "Q7. What is light?",
          responseChoice: [
            { responseId: "A", responseText: "Option A" },
            { responseId: "B", responseText: "Option B" },
            { responseId: "C", responseText: "Option C" },
            { responseId: "D", responseText: "Option D" },
          ],
          backgroundImg: "url('./not-visited.png')",
          cssName: "qbg-not-visited",
          noQuestionAttempt: 0,
          noQuestion: 7,
        },
        {
          questionId: 300008,
          questionDisplayId: "1011905064",
          questionType: "Multiple-Choice",
          questionTypeLabel: "Multiple Choice",
          sectionId: 566,
          sectionName: "Chemistry",
          sectionOrder: 2,
          sectionTime: 0,
          topicId: "1036",
          timeSpent: 0,
          correctAnswerMarks: 4,
          incorrectAnswerMarks: -1,
          notAnswerMarks: 0,
          questionBody: "Q8. Define an atom.",
          responseChoice: [
            { responseId: "A", responseText: "Option A" },
            { responseId: "B", responseText: "Option B" },
            { responseId: "C", responseText: "Option C" },
            { responseId: "D", responseText: "Option D" },
          ],
          backgroundImg: "url('./not-visited.png')",
          cssName: "qbg-not-visited",
          noQuestionAttempt: 0,
          noQuestion: 9,
        },
        {
          questionId: 300009,
          questionDisplayId: "1011905065",
          questionType: "Multiple-Choice",
          questionTypeLabel: "Multiple Choice",
          sectionId: 566,
          sectionName: "Chemistry",
          sectionOrder: 2,
          sectionTime: 0,
          topicId: "1037",
          timeSpent: 0,
          correctAnswerMarks: 4,
          incorrectAnswerMarks: -1,
          notAnswerMarks: 0,
          questionBody: "Q9. What is a molecule?",
          responseChoice: [
            { responseId: "A", responseText: "Option A" },
            { responseId: "B", responseText: "Option B" },
            { responseId: "C", responseText: "Option C" },
            { responseId: "D", responseText: "Option D" },
          ],
          backgroundImg: "url('./not-visited.png')",
          cssName: "qbg-not-visited",
          noQuestionAttempt: 0,
          noQuestion: 9,
        },
        {
          questionId: 300010,
          questionDisplayId: "1011905066",
          questionType: "Multiple-Choice",
          questionTypeLabel: "Multiple Choice",
          sectionId: 566,
          sectionName: "Chemistry",
          sectionOrder: 2,
          sectionTime: 0,
          topicId: "1038",
          timeSpent: 0,
          correctAnswerMarks: 4,
          incorrectAnswerMarks: -1,
          notAnswerMarks: 0,
          questionBody: "Q10. pH of neutral water?",
          responseChoice: [
            { responseId: "A", responseText: "Option A" },
            { responseId: "B", responseText: "Option B" },
            { responseId: "C", responseText: "Option C" },
            { responseId: "D", responseText: "Option D" },
          ],
          backgroundImg: "url('./not-visited.png')",
          cssName: "qbg-not-visited",
          noQuestionAttempt: 0,
          noQuestion: 9,
        },
        {
          questionId: 300011,
          questionDisplayId: "1011905067",
          questionType: "Multiple-Choice",
          questionTypeLabel: "Multiple Choice",
          sectionId: 566,
          sectionName: "Chemistry",
          sectionOrder: 2,
          sectionTime: 0,
          topicId: "1039",
          timeSpent: 0,
          correctAnswerMarks: 4,
          incorrectAnswerMarks: -1,
          notAnswerMarks: 0,
          questionBody: "Q11. What is an acid?",
          responseChoice: [
            { responseId: "A", responseText: "Option A" },
            { responseId: "B", responseText: "Option B" },
            { responseId: "C", responseText: "Option C" },
            { responseId: "D", responseText: "Option D" },
          ],
          backgroundImg: "url('./not-visited.png')",
          cssName: "qbg-not-visited",
          noQuestionAttempt: 0,
          noQuestion: 9,
        },
        {
          questionId: 300012,
          questionDisplayId: "1011905068",
          questionType: "Multiple-Choice",
          questionTypeLabel: "Multiple Choice",
          sectionId: 566,
          sectionName: "Chemistry",
          sectionOrder: 2,
          sectionTime: 0,
          topicId: "1040",
          timeSpent: 0,
          correctAnswerMarks: 4,
          incorrectAnswerMarks: -1,
          notAnswerMarks: 0,
          questionBody: "Q12. What is a base?",
          responseChoice: [
            { responseId: "A", responseText: "Option A" },
            { responseId: "B", responseText: "Option B" },
            { responseId: "C", responseText: "Option C" },
            { responseId: "D", responseText: "Option D" },
          ],
          backgroundImg: "url('./not-visited.png')",
          cssName: "qbg-not-visited",
          noQuestionAttempt: 0,
          noQuestion: 9,
        },
        {
          questionId: 300013,
          questionDisplayId: "1011905069",
          questionType: "Multiple-Choice",
          questionTypeLabel: "Multiple Choice",
          sectionId: 566,
          sectionName: "Chemistry",
          sectionOrder: 2,
          sectionTime: 0,
          topicId: "1041",
          timeSpent: 0,
          correctAnswerMarks: 4,
          incorrectAnswerMarks: -1,
          notAnswerMarks: 0,
          questionBody: "Q13. Chemical symbol for water?",
          responseChoice: [
            { responseId: "A", responseText: "Option A" },
            { responseId: "B", responseText: "Option B" },
            { responseId: "C", responseText: "Option C" },
            { responseId: "D", responseText: "Option D" },
          ],
          backgroundImg: "url('./not-visited.png')",
          cssName: "qbg-not-visited",
          noQuestionAttempt: 0,
          noQuestion: 9,
        },
        {
          questionId: 300014,
          questionDisplayId: "1011905070",
          questionType: "Multiple-Choice",
          questionTypeLabel: "Multiple Choice",
          sectionId: 566,
          sectionName: "Chemistry",
          sectionOrder: 2,
          sectionTime: 0,
          topicId: "1042",
          timeSpent: 0,
          correctAnswerMarks: 4,
          incorrectAnswerMarks: -1,
          notAnswerMarks: 0,
          questionBody: "Q14. What is a catalyst?",
          responseChoice: [
            { responseId: "A", responseText: "Option A" },
            { responseId: "B", responseText: "Option B" },
            { responseId: "C", responseText: "Option C" },
            { responseId: "D", responseText: "Option D" },
          ],
          backgroundImg: "url('./not-visited.png')",
          cssName: "qbg-not-visited",
          noQuestionAttempt: 0,
          noQuestion: 9,
        },
        {
          questionId: 300015,
          questionDisplayId: "1011905071",
          questionType: "Multiple-Choice",
          questionTypeLabel: "Multiple Choice",
          sectionId: 566,
          sectionName: "Chemistry",
          sectionOrder: 2,
          sectionTime: 0,
          topicId: "1043",
          timeSpent: 0,
          correctAnswerMarks: 4,
          incorrectAnswerMarks: -1,
          notAnswerMarks: 0,
          questionBody: "Q15. States of matter?",
          responseChoice: [
            { responseId: "A", responseText: "Option A" },
            { responseId: "B", responseText: "Option B" },
            { responseId: "C", responseText: "Option C" },
            { responseId: "D", responseText: "Option D" },
          ],
          backgroundImg: "url('./not-visited.png')",
          cssName: "qbg-not-visited",
          noQuestionAttempt: 0,
          noQuestion: 9,
        },
        {
          questionId: 300016,
          questionDisplayId: "1011905072",
          questionType: "Multiple-Choice",
          questionTypeLabel: "Multiple Choice",
          sectionId: 567,
          sectionName: "Biology",
          sectionOrder: 3,
          sectionTime: 0,
          topicId: "1044",
          timeSpent: 0,
          correctAnswerMarks: 4,
          incorrectAnswerMarks: -1,
          notAnswerMarks: 0,
          questionBody: "Q16. What is photosynthesis?",
          responseChoice: [
            { responseId: "A", responseText: "Option A" },
            { responseId: "B", responseText: "Option B" },
            { responseId: "C", responseText: "Option C" },
            { responseId: "D", responseText: "Option D" },
          ],
          backgroundImg: "url('./not-visited.png')",
          cssName: "qbg-not-visited",
          noQuestionAttempt: 0,
          noQuestion: 5,
        },
        {
          questionId: 300017,
          questionDisplayId: "1011905073",
          questionType: "Multiple-Choice",
          questionTypeLabel: "Multiple Choice",
          sectionId: 567,
          sectionName: "Biology",
          sectionOrder: 3,
          sectionTime: 0,
          topicId: "1045",
          timeSpent: 0,
          correctAnswerMarks: 4,
          incorrectAnswerMarks: -1,
          notAnswerMarks: 0,
          questionBody: "Q17. Function of DNA?",
          responseChoice: [
            { responseId: "A", responseText: "Option A" },
            { responseId: "B", responseText: "Option B" },
            { responseId: "C", responseText: "Option C" },
            { responseId: "D", responseText: "Option D" },
          ],
          backgroundImg: "url('./not-visited.png')",
          cssName: "qbg-not-visited",
          noQuestionAttempt: 0,
          noQuestion: 5,
        },
        {
          questionId: 300018,
          questionDisplayId: "1011905074",
          questionType: "Multiple-Choice",
          questionTypeLabel: "Multiple Choice",
          sectionId: 567,
          sectionName: "Biology",
          sectionOrder: 3,
          sectionTime: 0,
          topicId: "1046",
          timeSpent: 0,
          correctAnswerMarks: 4,
          incorrectAnswerMarks: -1,
          notAnswerMarks: 0,
          questionBody: "Q18. What is a cell?",
          responseChoice: [
            { responseId: "A", responseText: "Option A" },
            { responseId: "B", responseText: "Option B" },
            { responseId: "C", responseText: "Option C" },
            { responseId: "D", responseText: "Option D" },
          ],
          backgroundImg: "url('./not-visited.png')",
          cssName: "qbg-not-visited",
          noQuestionAttempt: 0,
          noQuestion: 5,
        },
        {
          questionId: 300019,
          questionDisplayId: "1011905075",
          questionType: "Multiple-Choice",
          questionTypeLabel: "Multiple Choice",
          sectionId: 567,
          sectionName: "Biology",
          sectionOrder: 3,
          sectionTime: 0,
          topicId: "1047",
          timeSpent: 0,
          correctAnswerMarks: 4,
          incorrectAnswerMarks: -1,
          notAnswerMarks: 0,
          questionBody: "Q19. Role of mitochondria?",
          responseChoice: [
            { responseId: "A", responseText: "Option A" },
            { responseId: "B", responseText: "Option B" },
            { responseId: "C", responseText: "Option C" },
            { responseId: "D", responseText: "Option D" },
          ],
          backgroundImg: "url('./not-visited.png')",
          cssName: "qbg-not-visited",
          noQuestionAttempt: 0,
          noQuestion: 5,
        },
        {
          questionId: 300020,
          questionDisplayId: "1011905076",
          questionType: "Multiple-Choice",
          questionTypeLabel: "Multiple Choice",
          sectionId: 567,
          sectionName: "Biology",
          sectionOrder: 3,
          sectionTime: 0,
          topicId: "1048",
          timeSpent: 0,
          correctAnswerMarks: 4,
          incorrectAnswerMarks: -1,
          notAnswerMarks: 0,
          questionBody: "Q20. What is respiration?",
          responseChoice: [
            { responseId: "A", responseText: "Option A" },
            { responseId: "B", responseText: "Option B" },
            { responseId: "C", responseText: "Option C" },
            { responseId: "D", responseText: "Option D" },
          ],
          backgroundImg: "url('./not-visited.png')",
          cssName: "qbg-not-visited",
          noQuestionAttempt: 0,
          noQuestion: 5,
        },
      ],
    },
  ],
};

const TestSimulator = () => {
  const isMobile = useIsMobile();

  const setTestData = useTestStore((state) => state.setTestData);
  const reset = useTestStore((state) => state.reset);
  const startQuestionTimer = useTestStore((state) => state.startQuestionTimer);
  const stopQuestionTimer = useTestStore((state) => state.stopQuestionTimer);
  const startTestTimer = useTestTimerStore((state) => state.startTestTimer);
  const stopTestTimer = useTestTimerStore((state) => state.stopTestTimer);

  useEffect(() => {
    reset();
    setTestData(dummyData?.obj?.[0]);
    startQuestionTimer();
    startTestTimer(dummyData?.obj?.[0]?.remainingTime);
    return () => {
      stopQuestionTimer();
      stopTestTimer();
    };
  }, []);

  return !isMobile ? <DesktopTestSimulator /> : <MobileTestSimulator />;
};

export default TestSimulator;
