export const gtmEvents = {
    verify_otp_button_click: "verify_otp_button_click",
    cancel_otp_button_click: "cancel_otp_button_click",
    otp_resend_button_click: "otp_resend_button_click",
    login_button_click: "login_button_click",
    login_signup_click: "login_signup_click",
    get_otp_button_click: "get_otp_button_click",
    forget_password_button_click: "forget_password_button_click",
    forget_password_submit_button_click: "forget_password_submit_button_click",
    all_courses_searchbar_click: "all_courses_searchbar_click",
    explore_features_button_click: "explore_features_button_click",
    contact_support_button_click: "contact_support_button_click",
    complete_profile_button_click: "complete_profile_button_click",
    delete_account_button_click: "delete_account_button_click",
    save_profile_button_click: "save_profile_button_click",
    continue_test_button_click: "continue_test_button_click",
    cancel_previous_test_modal_click: "cancel_previous_test_modal_click",
    send_support_button_click: "send_support_button_click",
    go_back_button_click: "go_back_button_click",
    start_topic_test_button_click: "start_topic_test_button_click",
    begin_now_test_button_click: "begin_now_test_button_click",
    cancel_topic_test_button_click: "cancel_topic_test_button_click",
    begin_mock_test_button_click: "begin_mock_test_button_click",
    start_mock_test_button_click: "start_mock_test_button_click",
    cancel_mock_test_button_click: "cancel_mock_test_button_click",
    get_app_android_button_click: "get_app_android_button_click",
    get_app_ios_button_click: "get_app_ios_button_click",
    jump_back_in_button_click: "jump_back_in_button_click",
    profile_menu_button_click: "profile_menu_button_click",
    all_courses_clear_filter_click: "all_courses_clear_filter_click",
    report_category_tab_click: "report_category_tab_click",
    report_test_detail_click: "report_test_detail_click",
    
    // Sidebar menu click events
    sidebar_dashboard_click: "sidebar_dashboard_click",
    sidebar_study_room_click: "sidebar_study_room_click",
    sidebar_exam_room_click: "sidebar_exam_room_click",
    sidebar_reports_click: "sidebar_reports_click",
    sidebar_all_courses_click: "sidebar_all_courses_click",
    sidebar_whats_new_click: "sidebar_whats_new_click",

    // page-view events
    dashboard_page_visit: "dashboard_page_visit",
    profile_page_visit: "profile_page_visit",
    smart_learning_page_visit: "smart_learning_page_visit",
    study_material_page_visit: "study_material_page_visit",
    topic_test_page_visit: "topic_test_page_visit",
    detail_report_topic_test_page_visit: "detail_report_topic_test_page_visit",
    mock_test_page_visit: "mock_test_page_visit",
    report_overview_page_visit: "report_overview_page_visit",
    detail_report_mock_test_page_visit: "detail_report_mock_test_page_visit",
    detail_report_class_test_page_visit: "detail_report_class_test_page_visit",
    detail_report_class_mock_test_page_visit: "detail_report_class_mock_test_page_visit",
    detail_report_learning_session_page_visit: "detail_report_learning_session_page_visit",
    detail_report_competitive_session_page_visit: "detail_report_competitive_session_page_visit",
    all_courses_page_visit: "all_courses_page_visit",




    //to-do:
    logout_button_click: "logout_button_click",
    all_courses_filter_category_click: "all_courses_filter_category_click",
    all_courses_card_click: "all_courses_card_click",
};
