export const gtmEvents: Record<string, any> = {
  verify_otp_button_click: "verify_otp_button_click",
  cancel_otp_button_click: "cancel_otp_button_click",
  otp_resend_button_click: "otp_resend_button_click",
  login_button_click: "login_button_click",
  login_signup_click: "login_signup_click",
  logout_button_click: "logout_button_click",
  get_otp_button_click: "get_otp_button_click",
  forget_password_button_click: "forget_password_button_click",
  forget_password_submit_button_click: "forget_password_submit_button_click",
  all_courses_searchbar_click: "all_courses_searchbar_click",
  explore_features_button_click: "explore_features_button_click",
  contact_support_button_click: "contact_support_button_click",
  complete_profile_button_click: "complete_profile_button_click",
  delete_account_button_click: "delete_account_button_click",
  save_profile_button_click: "save_profile_button_click",
  continue_test_button_click: "continue_test_button_click",
  cancel_previous_test_modal_click: "cancel_previous_test_modal_click",
  send_support_button_click: "send_support_button_click",
  go_back_button_click: "go_back_button_click",
  start_topic_test_button_click: "start_topic_test_button_click",
  begin_now_test_button_click: "begin_now_test_button_click",
  cancel_topic_test_button_click: "cancel_topic_test_button_click",
  begin_mock_test_button_click: "begin_mock_test_button_click",
  start_mock_test_button_click: "start_mock_test_button_click",
  cancel_mock_test_button_click: "cancel_mock_test_button_click",
  get_app_android_button_click: "get_app_android_button_click",
  get_app_ios_button_click: "get_app_ios_button_click",
  jump_back_in_button_click: "jump_back_in_button_click",
  profile_menu_button_click: "profile_menu_button_click",
  all_courses_clear_filter_click: "all_courses_clear_filter_click",
  report_category_tab_click: "report_category_tab_click",
  report_test_detail_click: "report_test_detail_click",
  all_courses_filter_category_click: "all_courses_filter_category_click",
  all_courses_card_click: "all_courses_card_click",
  invite_teacher_send_button_click: "invite_teacher_send_button_click",
  cancel_invite_teacher_send_button_click:"cancel_invite_teacher_send_button_click",
  send_feedback_button_click: "send_feedback_button_click",
  cancel_feedback_modal_click: "cancel_feedback_modal_click",
  send_rate_course_button_click: "send_rate_course_button_click",
  rate_course_button_click: "rate_course_button_click",
  tutorial_menu_click: "tutorial_menu_click",
  tutorial_video_link_click: "tutorial_video_link_click",
  close_tutorial_video_modal: "close_tutorial_video_modal",
  activity_view_test_modal_click: "activity_view_test_modal_click",
  activity_chart_day_click: "activity_chart_day_click",
  feature_banner_video_link_click: "feature_banner_video_link_click",
  feature_banner_tutorial_cards_click:"feature_banner_tutorial_cards_click",
  feature_banner_close_button_click: "feature_banner_close_button_click",

  // Sidebar menu click events
  sidebar_dashboard_click: "sidebar_dashboard_click",
  sidebar_study_room_click: "sidebar_study_room_click",
  sidebar_exam_room_click: "sidebar_exam_room_click",
  sidebar_reports_click: "sidebar_reports_click",
  sidebar_all_courses_click: "sidebar_all_courses_click",
  sidebar_whats_new_click: "sidebar_whats_new_click",

  // page-view events
  dashboard_page_visit: "dashboard_page_visit",
  profile_page_visit: "profile_page_visit",
  smart_learning_page_visit: "smart_learning_page_visit",
  study_material_page_visit: "study_material_page_visit",
  topic_test_page_visit: "topic_test_page_visit",
  detail_report_topic_test_page_visit: "detail_report_topic_test_page_visit",
  mock_test_page_visit: "mock_test_page_visit",
  report_overview_page_visit: "report_overview_page_visit",
  detail_report_mock_test_page_visit: "detail_report_mock_test_page_visit",
  detail_report_class_test_page_visit: "detail_report_class_test_page_visit",
  detail_report_class_mock_test_page_visit:"detail_report_class_mock_test_page_visit",
  detail_report_learning_session_page_visit:"detail_report_learning_session_page_visit",
  detail_report_competitive_session_page_visit:"detail_report_competitive_session_page_visit",
  all_courses_page_visit: "all_courses_page_visit",


  Smart_learning_topic_button_click: "Smart_learning_topic_button_click",
  competitive_session_button_click: "competitive_session_button_click",
  learning_session_button_click: "learning_session_button_click",
  cancel_competitive_session_button_click: "cancel_competitive_session_button_click",
  cancel_learning_session_button_click: "cancel_learning_session_button_click",
  start_learning_session_button_click: "start_learning_session_button_click",
  start_competitive_session_button_click: "start_competitive_session_button_click",
  next_competitive_session_button_click: "next_competitive_session_button_click",
  next_learning_session_button_click: "next_learning_session_button_click",
  competitive_session_Options_button_click: "competitive_session_Options_button_click",
  competitive_session_Instructions_button_click: "competitive_session_Instructions_button_click",
  Study_material_topic_button_click: "Study_material_topic_button_click",
  Study_material_content_item_click: "Study_material_content_item_click",
  close_content_modal_button_click: "close_content_modal_button_click",
  study_material_filter_button_click: "study_material_filter_button_click",
  topic_tree_expand_click: "topic_tree_expand_click",
  test_simulator_ask_tony_button_click: "test_simulator_ask_tony_button_click",
  test_simulator_clear_response_button_click: "test_simulator_clear_response_button_click",
  test_simulator_mark_for_review_button_click: "test_simulator_mark_for_review_button_click",
  test_simulator_next_button_click: "test_simulator_next_button_click",
  test_simulator_previous_button_click: "test_simulator_previous_button_click",
  test_simulator_question_palette_click: "test_simulator_question_palette_click",
  test_view_exit_button_click: "test_view_exit_button_click",
  test_view_support_button_click: "test_view_support_button_click",
  test_simulator_finish_test_button_click: "test_simulator_finish_test_button_click",
  test_simulator_submit_now_button_click: "test_simulator_submit_now_button_click",
  test_simulator_save_and_continue_button_click: "test_simulator_save_and_continue_button_click",
  test_simulator_cancel_button_click: "test_simulator_cancel_button_click",
  test_simulator_fullscreen_submit_button_click: "test_simulator_fullscreen_submit_button_click",
  test_simulator_fullscreen_reEnter_button_click: "test_simulator_fullscreen_reEnter_button_click",
  test_simulator_auto_submit_button_click: "test_simulator_auto_submit_button_click",

  //need to do guest test sbmit modal events

  proceed_to_pay_button_click: "proceed_to_pay_button_click",
  upgrade_button_click: "upgrade_button_click",
  renew_button_click: "renew_button_click",
  apply_promo_code_button_click: "apply_promo_code_button_click",
  guest_verify_otp_button_click: "guest_verify_otp_button_click",
  // guest_cancel_otp_button_click: "guest_cancel_otp_button_click",
  // guest_otp_resend_button_click: "guest_otp_resend_button_click",
  
  
};


